version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=samir
      - MYSQL_PASSWORD=Password@01
      - MYSQL_DATABASE=react
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Password@01
      MYSQL_DATABASE: react
      MYSQL_USER: samir
      MYSQL_PASSWORD: Password@01
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
